[package]
authors = ["Pavel Ivanov <mr.pavel.ivanov@gmail.com>"]
categories = ["command-line-utilities"]
description = "Utility for viewing json-formatted log files."
keywords = ["cli", "human", "log"]
name = "hl"
version = "0.7.2-alpha.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
capnpc = "0.13"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
atoi = "0.3.2"
bincode = "1.3"
bitmask = "0.5"
capnp = "0.13"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
closure = "0.3"
directories = "0.8"
error-chain = "0.12"
flate2 = "1.0"
generic-array = "0.14"
heapless = "0.5.5"
hex = "0.4"
itertools = "0.9"
crossbeam-utils = "0.7"
crossbeam-queue = "0.2"
crossbeam-channel = "0.4"
isatty = "0.1"
num_cpus = "1.0"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
sha2 = "0.9"
shellwords = "1.1"
signal-hook = "0.1"

[dependencies.itoa]
version = "0.4.3"
default-features = false

[dev-dependencies]
criterion = "0.3"
diligent-date-parser = "0.1"
regex = "1"

[profile.release]
debug = false

[[bench]]
name = "ts_parse"
harness = false

[[bench]]
name = "ts_format"
harness = false