name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO: cargo
      TARGET_FLAGS: ''
      TARGET_DIR: ./target

    strategy:
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: hl
            asset_name: hl-linux.tar.gz
          - name: windows
            os: windows-latest
            artifact_name: hl.exe
            asset_name: hl-windows.zip
          - name: macos
            os: macos-latest
            artifact_name: hl
            asset_name: hl-macos.tar.gz

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Cross
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cross
          echo "::set-env name=CARGO::cross"
          echo "::set-env name=TARGET_FLAGS::--target ${{ matrix.target }}"
          echo "::set-env name=TARGET_DIR::./target/${{ matrix.target }}"

      - name: Build
        run: ${{ env.CARGO }} build --release --locked --verbose ${{ env.TARGET_FLAGS }}

      - name: Package
        if: matrix.os != 'windows-latest'
        run: tar -C "${{ env.TARGET_DIR }}/release" -cz -f "${{ matrix.asset_name }}" "${{ matrix.artifact_name }}"

      - name: Package
        if: matrix.os == 'windows-latest'
        run: 7z a "${{ matrix.asset_name }}" "${{ env.TARGET_DIR }}/release/${{ matrix.artifact_name }}"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

      - name: Checkout homebrew-tap repository
        if: matrix.os == 'macos-latest'
        uses: actions/checkout@v2
        with:
          repository: pamburus/homebrew-tap
          path: homebrew-tap

      - name: Download tera
        if: matrix.os == 'macos-latest'
        run: curl -sSfL https://github.com/guangie88/tera-cli/releases/download/v0.4.1/tera-cli-v0.4.1-x86_64-apple-darwin.tar.gz | tar -x --strip-components 1 '*/tera'

      - name: Fetch version
        if: matrix.os == 'macos-latest'
        run: |
          echo "::set-env name=VERSION::$(echo ${{ github.ref }} | sed 's/^refs\/tags\/v\(.*\)$/\1/g')"

      - name: Render homebrew formula template
        if: matrix.os == 'macos-latest'
        run: |
          version=${VERSION} \
          sha256=$(openssl sha256 "${{ matrix.asset_name }}" | cut -d ' ' -f2) \
          ./tera -f templates/homebrew/hl.rb.tpl --env >homebrew-tap/hl-v${VERSION}.rb

      - name: Commit homebrew formula
        if: matrix.os == 'macos-latest'
        run: |
          (cd homebrew-tap && git add . && git commit -m "new: formula for hl v${VERSION}")

      - name: Push changes in homebrew-tap
        if: matrix.os == 'macos-latest'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: pamburus/homebrew-tap
          directory: homebrew-tap
